In [2]:
import pandas as pd

In [3]:
import sys  

reload(sys)  
sys.setdefaultencoding('utf8')

cc_14 = pd.read_excel('./carga_cont_2014_0.xlsx')
cc_15 = pd.read_excel('./carga_cont_2015_0.xlsx')
cc_16 = pd.read_excel('./carga_cont_2016_0.xlsx')
cc_17 = pd.read_excel('./carga_cont_2017_1.xlsx')
cc_18 = pd.read_excel('./carga_cont_2018_2.xlsx')
cc_14['Año'] = 2014; cc_15['Año'] = 2015; cc_16['Año'] = 2016; cc_17['Año'] = 2017; cc_18['Año'] = 2018;

cc = pd.concat([cc_14, cc_15, cc_16, cc_17, cc_18])

df = cc.groupby(['Año', 'Puerto']).sum()[['Carga TEUs']].unstack()

In [5]:
df

         Carga TEUs                                                    \
Puerto Bahía Blanca Bahía Blanca  Buenos Aires Concepción del Uruguay
Año
2014        13992.0           NaN     504372.0                    NaN
2015        11727.0           NaN     474857.0                    NaN
2016        17839.0           NaN     441769.0                  140.0
2017        13207.0           NaN     421170.0                  439.0
2018            NaN        4611.0     213500.0                    NaN

                                                                            \
Puerto Corrientes  Deseado  Dock Sud Euroamerica  Exolgan Formosa La Plata
Año
2014        674.0   6430.0  205634.0         0.0      NaN     NaN      0.0
2015        434.0   9402.0  209761.0       199.0      NaN     NaN      0.0
2016        411.0   7422.0  220446.0         4.0      NaN    52.0      0.0
2017       1290.0  11217.0  257788.0         NaN      NaN     0.0      NaN
2018        376.0   3938.0   77826.0         NaN  74100.0     NaN      NaN

                                                               \
Puerto   Madryn Mar del Plata   Molca Rosario - Muelle ENAPRO
Año
2014    15584.0           0.0  4551.0                 14372.0
2015    12317.0        2530.0  4469.0                 15713.0
2016    14648.0        6905.0     0.0                 28143.0
2017    16655.0        7916.0    35.0                 33516.0
2018    13002.0        4322.0     NaN                 19372.0


Puerto San Antonio Este San Pedro Santa Fe Terminal Zárate  Ushuaia
Año
2014            11362.0     316.0    686.0         67109.0  30803.0
2015             7719.0    1156.0      NaN         63499.0  30683.0
2016            12315.0       NaN    410.0         66364.0  33567.0
2017            12318.0    1130.0      0.0         58830.0  25960.0
2018            14245.0     556.0      NaN         25526.0  13826.0

In [49]:
cnc.groupby(u'Tipo de Operación').sum().sort_values(by = 'Cantidades')

                                 Cantidades      Año
Tipo de Operación
Vehículos Cabotaje Entrado     1.500000e+02     6047
Vehículos Cabotaje Salido      1.500000e+02     6047
Vehículos Expo                 7.268220e+05    62479
Vehículos Impo                 1.274658e+06    90709
Tránsito                       6.404272e+06    70550
Transbordo / Tránsito Entrado  1.687898e+07   320499
Transbordo / Tránsito Salido   2.822521e+07   528120
Importación                    9.854757e+07  2156971
Cabotaje Entrado               1.081343e+08  1884673
Cabotaje Salido                1.112100e+08  1193290
Exportación                    3.823373e+08  3783579

In [35]:
cnc_14 = pd.read_excel('./carga_ncont_2014_1.xlsx')
cnc_15 = pd.read_excel('./carga_ncont_2015_1.xlsx')
cnc_16 = pd.read_excel('./carga_ncont_2016_1.xlsx')
cnc_17 = pd.read_excel('./carga_ncont_2017_3.xlsx')
cnc_18 = pd.read_excel('./carga_ncont_2018_7.xlsx')
cnc_14['Año'] = 2014; cnc_15['Año'] = 2015; cnc_16['Año'] = 2016; cnc_17['Año'] = 2017; cnc_18['Año'] = 2018;

cnc = pd.concat([cnc_14, cnc_15, cnc_16, cnc_17, cnc_18])

In [36]:
cnc[['Puerto']].drop_duplicates()#.to_csv('puertos_for_georref.csv', index = False)

                                            Puerto
0                                           Arauco
1                           Axion Energy (Campana)
5                                     Bahía Blanca
31                                 Bunge (Ramallo)
36                     Campana - Muelle Provincial
37                                       Carboclor
41                   Central Térmica - San Nicolás
43                                      Delta Dock
47                                        Dock Sud
54                                     Euroamerica
60                                        La Plata
71                                   Mar del Plata
72                      Mar del Plata - Muelle YPF
73                                           Molca
74                                         Odfjell
76                                    Papel Prensa
77                                         Quequén
82                           Regasificador Escobar
84                                           Rhasa
86                                         Rosales
88                 San Nicolás - Muelle Provincial
104                                      San Pedro
106                                        Siderar
111                                        Siderca
113                                Terminal Zárate
115                                          Vitco
117                                       Xstorage
120                                  ACA (Vilelas)
121               Barranqueras - Muelle Provincial
123                      Barranqueras - Muelle YPF
..                                             ...
236              Pan American Energy (San Lorenzo)
238                                      Profertil
239                                         Renova
241                        Rosario - Muelle ENAPRO
245          San Lorenzo - San Martín - Muelle YPF
250                                       Santa Fe
255                            Shell (Arroyo Seco)
257                                     Terminal 6
266                      Termoeléctrica San Martín
267                                       Vicentín
272              Villa Constitución - Muelle EAPVC
275                                   Cruz del Sur
276                                     Río Cullen
277                                        Ushuaia
278                           Ushuaia - Muelle YPF
401                 Barranqueras - Muelle Elevador
429              Coop. "La Ganadera" Gral. Ramírez
436                               La Paz - Márquez
437                                    Paraná Iron
722                               Maná Puerto Buey
211                               Oil Combustibles
250           Terminal de Fertilizantes Argentinos
412                         Diamante - Muelle EAPD
180  Central Térmica Sorrento - Generación Rosario
70                                     Petromining
122                          Comodoro Rivadavia
137                        Concepción del Uruguay
147                              Maná Puerto Buey
254             Cargill (Villa Gobernador Gálvez)
492                                Unidades VI-VII

[95 rows x 1 columns]

In [40]:
# df = cnc.loc[cnc[u'Tipo de Operación'].isin([u'Importación', u'Exportación'])].groupby(['Año', 'Rubro', 'Puerto', u'Tipo de Operación']).sum()[['Cantidades']]#.unstack([1, 2])
# df = cnc.loc[cnc[u'Tipo de Operación'].isin([u'Importación', u'Exportación', 'Cabotaje Salido'])].groupby(['Año', 'Puerto', u'Tipo de Operación']).sum()[['Cantidades']]#.unstack([1, 2])
df = cnc.loc[cnc[u'Tipo de Operación'].isin([u'Importación', u'Exportación', 'Cabotaje Salido'])].groupby(['Año', 'Puerto']).sum()[['Cantidades']]#.unstack([1, 2])

pd.options.display.max_rows = 999
result = df.loc[2017].sort_values(by = 'Cantidades', ascending = False)

# 100*(result/result.sum())[['Cantidades']]#.cumsum()
Port_total_2014 = result

In [12]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [118]:
# Load info, format coordinates column

georref_ports = pd.read_csv('./puertos_for_georref_edit.csv', encoding = 'utf-8').dropna()
georref_ports = georref_ports.merge(Port_total_2014, on = 'Puerto', how = 'left').dropna()
georref_ports['coordinates'] = [[float(i) for i in c.split(',')] for c in georref_ports['location']]
georref_ports['coordinates'] = [l[::-1] for l in georref_ports['coordinates'].values] # reverse lat lon

In [120]:
### Make up columns that make a feature: geometry, type and properties

georref_ports['geometry'] = [dict({"type": "Point", "coordinates": c}) for c in georref_ports['coordinates']]
georref_ports['type'] = 'Feature'
georref_ports['properties'] = [dict({"Country": "ARG", "Cantidades": x}) for x in georref_ports['Cantidades']]

In [121]:
import ast

geojson_df = pd.DataFrame(columns = ["features"])
geojson_df["features"] = ast.literal_eval(georref_ports[['geometry', 'type', 'properties']].to_json(orient = 'records'))

In [122]:
import json

r = dict({
  "type": "FeatureCollection",
  "features": ast.literal_eval(georref_ports[['geometry', 'type', 'properties']].to_json(orient = 'records'))
})

with open('test.geojson', 'w') as outfile:
    json.dump(r, outfile)

In [ ]:
from mapbox import Uploader
import json
import os
import unidecode

username = 'matuteiglesias'
token = 'sk.eyJ1IjoibWF0dXRlaWdsZXNpYXMiLCJhIjoiY2puODA4bW8xMGV1dzNrcGtiOGp6NXQ5aCJ9.DohKmjn_o6MK1Y4Q5FG8ew'

files = os.listdir('./Preguntas_json/')
names = [name.split('.')[0] for name in files]
names = [unidecode.unidecode_expect_nonascii(name) for name in names]

for i in range(len(files))[3:]:
#     json_path = './test/'+name+'.geojson'
    print names[i]
    data = json.load(open('./'+files[i]))
#     data.pop('crs', None)

    with open('./upload_data.geojson', 'w') as outfile:
        json.dump(data, outfile)

    service = Uploader(access_token=token)
    with open('./upload_data.geojson', 'r') as src:
        # Acquisition of credentials, staging of data, and upload
        # finalization is done by a single method in the Python SDK.
        upload_resp = service.upload(src, username+'.'+names[i][:10])